# Generated by Django 5.1.1 on 2024-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Item title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Item description')),
            ],
        ),
    ]
